{
 "title": "Smartmeter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Phase", "label": "phase", "query": "1,2,3" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Consumed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "smart_meter_current_total_reading"
    }
   ]
  },
  {
   "title": "Cost 3 weeks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(smart_meter_current_total_reading[3w]) * 0.2738"
    }
   ]
  },
  {
   "title": "Current Power",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 1 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smart_meter_current_total_power"
    }
   ]
  },
  {
   "title": "Power per Phase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "smart_meter_power{phase!=\"all\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Consumed last week",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(smart_meter_current_total_reading[1w])"
    }
   ]
  },
  {
   "title": "Cost last week",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(smart_meter_current_total_reading[1w]) * 0.2738"
    }
   ]
  },
  {
   "title": "Consumed last 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(smart_meter_current_total_reading[24h])"
    }
   ]
  },
  {
   "title": "Cost last 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(smart_meter_current_total_reading[1d]) * 0.2738"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Power Phase $Phase",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "repeat": "Phase",
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smart_meter_power{phase=\"$Phase\"}"
    }
   ]
  },
  {
   "title": "Power Phase $Phase",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smart_meter_power{phase=\"$Phase\"}"
    }
   ]
  },
  {
   "title": "Power Phase $Phase",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smart_meter_power{phase=\"$Phase\"}"
    }
   ]
  },
  { "title": "Voltage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Voltage Phase $Phase",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "repeat": "Phase",
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "smart_meter_voltage{phase=\"$Phase\"}"
    }
   ]
  },
  {
   "title": "Voltage Phase $Phase",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "smart_meter_voltage{phase=\"$Phase\"}"
    }
   ]
  },
  {
   "title": "Voltage Phase $Phase",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "smart_meter_voltage{phase=\"$Phase\"}"
    }
   ]
  },
  { "title": "Consumption over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Energy consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "rate(smart_meter_current_total_reading{}[5m]) * 60",
     "legendFormat": "Consumption"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "smart_meter_voltage", "legendFormat": "Phase: {{phase}}" }
   ]
  }
 ]
}